name: Build and deploy Fullstack App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install & build frontend
      - name: Install frontend dependencies and build
        run: |
          cd app-frontend
          npm install
          npm run build

      # 4. Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd app-backend
          npm install

      # 5. Move frontend build into backend so Express can serve it
      - name: Copy frontend build to backend
        run: |
          rm -rf app-backend/build
          cp -r app-frontend/build app-backend/

      # 6. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      # 7. Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cloud-video-app121'   # 🔹 your Azure App name
          slot-name: 'production'
          package: app-backend
